#!/usr/bin/env python3
"""
generate_demiurge_offline.py
Self-contained — all citations are embedded in source code. No network calls.
Generates assets/texts/demiurge/{sector}.json with >= 200 entries each.

Usage:
    python3 tools/generate_demiurge_offline.py

Each sector entry format:
    { "opening": str, "citation": str, "author": str, "closing": str }

Generation strategy:
    Each sector defines raw_quotes (citation, author pairs), themed openings,
    and themed closings. Entries are generated by systematic pairing across
    multiple passes until target >= 200 is reached. Each (quote, opening,
    closing) triple is unique per entry.
"""

import json
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
OUTPUT_DIR = SCRIPT_DIR.parent / "assets" / "texts" / "demiurge"
TARGET = 200


# ---------------------------------------------------------------------------
def generate_entries(raw_quotes, openings, closings, target=TARGET):
    """Generate >= target unique (opening, citation, author, closing) dicts."""
    entries = []
    used = set()  # (quote_idx, opening_idx, closing_idx)
    n_o = len(openings)
    n_c = len(closings)

    pass_num = 0
    max_passes = n_o * n_c  # upper bound — ensures termination
    while len(entries) < target and pass_num < max_passes:
        for q_idx, (citation, author) in enumerate(raw_quotes):
            if len(entries) >= target:
                break
            o_idx = (q_idx * 3 + pass_num * 7) % n_o
            c_idx = (q_idx * 5 + pass_num * 11 + 3) % n_c
            key = (q_idx, o_idx, c_idx)
            if key not in used:
                used.add(key)
                entries.append({
                    "opening": openings[o_idx],
                    "citation": citation,
                    "author": author,
                    "closing": closings[c_idx],
                })
        pass_num += 1

    return entries


# ===========================================================================
# GIARDINO — Garden / North sector
# Themes: Stoic and Epicurean philosophy, mortality, wisdom, inner life
# Authors: Epicurus, Marcus Aurelius, Seneca, Plato, Aristotle, Epictetus
# ===========================================================================

GIARDINO_QUOTES = [
    # ── Epicurus ──────────────────────────────────────────────────────────
    ("Do not spoil what you have by desiring what you have not; remember that what you now have was once among the things you only hoped for.", "Epicurus"),
    ("It is not so much our friends' help that helps us as the confidence of their help.", "Epicurus"),
    ("Nothing is enough for the man to whom enough is too little.", "Epicurus"),
    ("Death is nothing to us: when we exist, death is not yet present, and when death is present, then we do not exist.", "Epicurus"),
    ("The greater the difficulty, the more glory in surmounting it.", "Epicurus"),
    ("He who is not contented with what he has would not be contented with what he would like to have.", "Epicurus"),
    ("Vain is the word of a philosopher which does not heal any suffering of man.", "Epicurus"),
    ("Of all the things which wisdom provides to make us entirely happy, much the greatest is the possession of friendship.", "Epicurus"),
    ("I have never wished to cater to the crowd; for what I know they do not approve, and what they approve I do not know.", "Epicurus"),
    ("Let no one be slow to seek wisdom when he is young nor weary in the search thereof when he has grown old.", "Epicurus"),
    ("A free life cannot acquire many possessions, because this is not easy to do without servility to mobs or monarchs.", "Epicurus"),
    ("The fool's life is empty of gratitude and full of fears; its course lies wholly toward the future.", "Epicurus"),
    ("It is better for you to be free of fear lying upon a pallet, than to have a golden couch and a rich table and be full of trouble.", "Epicurus"),
    ("We must laugh and philosophize at the same time and keep up our household duties and employ our other faculties.", "Epicurus"),
    ("The art of living well and the art of dying well are one.", "Epicurus"),
    ("We should look for someone to eat and drink with before looking for something to eat and drink.", "Epicurus"),
    ("It is possible to provide security against other ills, but as far as death is concerned, we men live in a city without walls.", "Epicurus"),
    ("He who has peace of mind disturbs neither himself nor another.", "Epicurus"),
    ("The wise man can lose nothing he has. He has everything stored within himself.", "Epicurus"),
    ("The beginning and the greatest good is prudence.", "Epicurus"),
    ("Accustom yourself to believing that death is nothing to us.", "Epicurus"),
    ("Misfortune seldom intrudes upon the wise man; his greatest and highest interests are directed by reason.", "Epicurus"),
    ("Luxurious food and drinks do not produce freedom from harm and a healthy condition in the flesh.", "Epicurus"),
    ("Of all things which wisdom provides to make life entirely happy, much the greatest is the possession of friendship.", "Epicurus"),
    ("The greatest fruit of self-sufficiency is freedom.", "Epicurus"),

    # ── Marcus Aurelius (Meditations) ────────────────────────────────────
    ("You have power over your mind, not outside events. Realize this, and you will find strength.", "Marcus Aurelius"),
    ("The impediment to action advances action. What stands in the way becomes the way.", "Marcus Aurelius"),
    ("Very little is needed to make a happy life; it is all within yourself, in your way of thinking.", "Marcus Aurelius"),
    ("Waste no more time arguing about what a good man should be. Be one.", "Marcus Aurelius"),
    ("If you are distressed by anything external, the pain is not due to the thing itself, but to your estimate of it.", "Marcus Aurelius"),
    ("Begin at once to live, and count each separate day as a separate life.", "Marcus Aurelius"),
    ("It is not death that a man should fear, but he should fear never beginning to live.", "Marcus Aurelius"),
    ("Perfection of character is this: to live each day as if it were your last, without frenzy, without apathy, without pretense.", "Marcus Aurelius"),
    ("The object of life is not to be on the side of the majority, but to escape finding oneself in the ranks of the insane.", "Marcus Aurelius"),
    ("Confine yourself to the present.", "Marcus Aurelius"),
    ("Nowhere can man find a quieter or more untroubled retreat than in his own soul.", "Marcus Aurelius"),
    ("The universe is transformation; life is opinion.", "Marcus Aurelius"),
    ("Loss is nothing else but change, and change is Nature's delight.", "Marcus Aurelius"),
    ("To live happily is an inward power of the soul.", "Marcus Aurelius"),
    ("Never esteem anything as of advantage to you that will make you break your word or lose your self-respect.", "Marcus Aurelius"),
    ("When you arise in the morning, think of what a precious privilege it is to be alive — to breathe, to think, to enjoy, to love.", "Marcus Aurelius"),
    ("Dwell on the beauty of life. Watch the stars, and see yourself running with them.", "Marcus Aurelius"),
    ("The first rule is to keep an untroubled spirit. The second is to look things in the face and know them for what they are.", "Marcus Aurelius"),
    ("Receive without pride, relinquish without struggle.", "Marcus Aurelius"),
    ("If it is not right, do not do it; if it is not true, do not say it.", "Marcus Aurelius"),
    ("Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.", "Marcus Aurelius"),
    ("How much time he gains who does not look to see what his neighbour says or does or thinks.", "Marcus Aurelius"),
    ("The happiness of your life depends upon the quality of your thoughts.", "Marcus Aurelius"),
    ("Look within. Within is the fountain of good, and it will ever bubble up, if thou wilt ever dig.", "Marcus Aurelius"),
    ("He who lives in harmony with himself lives in harmony with the universe.", "Marcus Aurelius"),
    ("The soul becomes dyed with the colour of its thoughts.", "Marcus Aurelius"),
    ("Be tolerant with others and strict with yourself.", "Marcus Aurelius"),
    ("The best revenge is to be unlike him who performed the injury.", "Marcus Aurelius"),
    ("Because your own strength is unequal to the task, do not assume that it is beyond the powers of man.", "Marcus Aurelius"),
    ("All is as thinking makes it so.", "Marcus Aurelius"),
    ("You could leave life right now. Let that determine what you do and say and think.", "Marcus Aurelius"),
    ("What we cannot bear removes us from life; what lasts can be borne.", "Marcus Aurelius"),
    ("Do what nature requires. Start at once, if possible, and don't look to see if people will know about it.", "Marcus Aurelius"),
    ("Do not indulge in dreams of what you have not, but count the blessings actually at hand.", "Marcus Aurelius"),
    ("Look back over the past, with its changing empires that rose and fell, and you can foresee the future, too.", "Marcus Aurelius"),

    # ── Seneca (Epistulae Morales, De Vita Beata) ─────────────────────────
    ("It is not the man who has too little, but the man who craves more, that is poor.", "Seneca"),
    ("We suffer more in imagination than in reality.", "Seneca"),
    ("If a man knows not to which port he sails, no wind is favorable.", "Seneca"),
    ("The greatest obstacle to living is expectancy, which hangs upon tomorrow and loses today.", "Seneca"),
    ("He who is brave is free.", "Seneca"),
    ("All cruelty springs from weakness.", "Seneca"),
    ("Luck is what happens when preparation meets opportunity.", "Seneca"),
    ("Leisure without books is death, and burial of a man alive.", "Seneca"),
    ("He is a wise man who does not grieve for the things which he has not, but rejoices for those which he has.", "Seneca"),
    ("As is a tale, so is life: not how long it is, but how good it is, is what matters.", "Seneca"),
    ("Time heals what reason cannot.", "Seneca"),
    ("Death is the wish of some, the relief of many, and the end of all.", "Seneca"),
    ("It is more fitting for a man to laugh at life than to lament over it.", "Seneca"),
    ("The day which we fear as our last is but the birthday of eternity.", "Seneca"),
    ("Everything, Lucilius, belongs to others; time alone is ours.", "Seneca"),
    ("Our plans miscarry because they have no aim. When a man does not know what harbour he is making for, no wind is the right wind.", "Seneca"),
    ("The whole future lies in uncertainty: live immediately.", "Seneca"),
    ("True happiness is to enjoy the present, without anxious dependence upon the future.", "Seneca"),
    ("While we delay, life passes by.", "Seneca"),
    ("Nowhere is the man who is everywhere.", "Seneca"),
    ("No man is crushed by misfortune unless he has first been deceived by prosperity.", "Seneca"),
    ("Associate with those who will make a better man of you.", "Seneca"),
    ("Recede in te ipse quantum potes — Retire into yourself as much as possible.", "Seneca"),
    ("The things that make life happy are things in our own power.", "Seneca"),
    ("Be harsh with yourself at times. Even in the midst of leisure, beware of listlessness.", "Seneca"),
    ("There is nothing more lamentable than a man who wastes his time traveling around the world when he has enough to do in himself.", "Seneca"),
    ("A multitude is the enemy of great minds.", "Seneca"),
    ("He who has made a fair compact with poverty is rich.", "Seneca"),
    ("It is not enough to reach for the laurel. One must deserve to wear it.", "Seneca"),
    ("Philosophy calls for simple living, not for doing penance, and the simple life need not be a crude one.", "Seneca"),

    # ── Plato (Dialogues) ────────────────────────────────────────────────
    ("The measure of a man is what he does with power.", "Plato"),
    ("The soul takes nothing with her to the next world but her education and culture.", "Plato"),
    ("Wise men talk because they have something to say; fools, because they have to say something.", "Plato"),
    ("The first and greatest victory is to conquer yourself; to be conquered by yourself is of all things most shameful and vile.", "Plato"),
    ("Courage is knowing what not to fear.", "Plato"),
    ("A good decision is based on knowledge, not on numbers.", "Plato"),
    ("We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.", "Plato"),
    ("Knowledge which is acquired under compulsion obtains no hold on the mind.", "Plato"),
    ("Philosophy begins in wonder.", "Plato"),
    ("The price good men pay for indifference to public affairs is to be ruled by evil men.", "Plato"),
    ("He who commits injustice is ever made more wretched than he who suffers it.", "Plato"),
    ("Geometry will draw the soul toward truth and create the spirit of philosophy.", "Plato"),
    ("The direction in which education starts a man will determine his future life.", "Plato"),
    ("No evil can happen to a good man, either in life or after death.", "Plato"),
    ("Good actions give strength to ourselves and inspire good actions in others.", "Plato"),
    ("The beginning is the most important part of the work.", "Plato"),
    ("There is no harm in repeating a good thing.", "Plato"),
    ("The greatest wealth is to live content with little.", "Plato"),
    ("Opinion is the medium between knowledge and ignorance.", "Plato"),
    ("Thinking is the talking of the soul with itself.", "Plato"),
    ("Human behavior flows from three main sources: desire, emotion, and knowledge.", "Plato"),
    ("Those who tell the stories rule society.", "Plato"),
    ("Excess of liberty, whether it lies in state or individuals, seems only to pass into excess of slavery.", "Plato"),
    ("All learning has an emotional base.", "Plato"),
    ("The unexamined life is not worth living.", "Plato"),

    # ── Aristotle ────────────────────────────────────────────────────────
    ("Excellence is never an accident. It is always the result of high intention, sincere effort, and intelligent execution.", "Aristotle"),
    ("We are what we repeatedly do. Excellence, then, is not an act, but a habit.", "Aristotle"),
    ("Nature does nothing in vain.", "Aristotle"),
    ("Knowing yourself is the beginning of all wisdom.", "Aristotle"),
    ("We cannot learn without pain.", "Aristotle"),
    ("Hope is a waking dream.", "Aristotle"),
    ("The energy of the mind is the essence of life.", "Aristotle"),
    ("In all things of nature there is something of the marvelous.", "Aristotle"),
    ("Man is by nature a social animal.", "Aristotle"),
    ("The roots of education are bitter, but the fruit is sweet.", "Aristotle"),
    ("Happiness depends upon ourselves.", "Aristotle"),
    ("The educated differ from the uneducated as much as the living differ from the dead.", "Aristotle"),
    ("Pleasure in the job puts perfection in the work.", "Aristotle"),
    ("No great mind has ever existed without a touch of madness.", "Aristotle"),
    ("Those who know, do. Those that understand, teach.", "Aristotle"),
    ("The aim of art is to represent not the outward appearance of things, but their inward significance.", "Aristotle"),
    ("I count him braver who overcomes his desires than him who conquers his enemies, for the hardest victory is over self.", "Aristotle"),
    ("The ideal man bears the accidents of life with dignity and grace, making the best of circumstances.", "Aristotle"),
    ("Friendship is a single soul dwelling in two bodies.", "Aristotle"),
    ("It is the mark of an educated mind to be able to entertain a thought without accepting it.", "Aristotle"),
    ("The ultimate value of life depends upon awareness and the power of contemplation rather than upon mere survival.", "Aristotle"),
    ("Without friends, no one would want to live, even if he had all other goods.", "Aristotle"),
    ("Dignity does not consist in possessing honors, but in deserving them.", "Aristotle"),
    ("The high-minded man must care more for truth than for what people think.", "Aristotle"),
    ("A friend to all is a friend to none.", "Aristotle"),
    ("The whole is more than the sum of its parts.", "Aristotle"),
    ("Patience is bitter, but its fruit is sweet.", "Aristotle"),
    ("Courage is a mean with regard to fear and confidence.", "Aristotle"),
    ("Character may almost be called the most effective means of persuasion.", "Aristotle"),
    ("All human actions have one or more of these seven causes: chance, nature, compulsions, habit, reason, passion, desire.", "Aristotle"),

    # ── Epictetus (Enchiridion, Discourses) ──────────────────────────────
    ("No man is free who is not master of himself.", "Epictetus"),
    ("Make the best use of what is in your power, and take the rest as it happens.", "Epictetus"),
    ("Seek not the good in external things; seek it within yourself.", "Epictetus"),
    ("It's not what happens to you, but how you react to it that matters.", "Epictetus"),
    ("First say to yourself what you would be; and then do what you have to do.", "Epictetus"),
    ("We cannot choose our external circumstances, but we can always choose how we respond to them.", "Epictetus"),
    ("Don't explain your philosophy. Embody it.", "Epictetus"),
    ("Wealth consists not in having great possessions, but in having few wants.", "Epictetus"),
    ("Of all existing things some are in our power, and others are not in our power.", "Epictetus"),
    ("The world turns aside to let any man pass who knows where he is going.", "Epictetus"),
    ("Freedom is not achieved by satisfying desire, but by eliminating it.", "Epictetus"),
    ("Men are disturbed not by the things which happen, but by the opinions about the things.", "Epictetus"),
    ("If you want to improve, be content to be thought foolish and stupid.", "Epictetus"),
    ("Never say that I have lost it; say I have returned it.", "Epictetus"),
    ("There is only one way to happiness and that is to cease worrying about things which are beyond the power of our will.", "Epictetus"),
    ("Seek not that the things which happen should happen as you wish; but wish the things which happen to be as they are.", "Epictetus"),
    ("It is impossible for a man to learn what he thinks he already knows.", "Epictetus"),
    ("People are not disturbed by things, but by their opinions about things.", "Epictetus"),
    ("Any person capable of angering you becomes your master.", "Epictetus"),
    ("Let silence be your goal for the most part; say only what is necessary.", "Epictetus"),
    ("Practice yourself in little things; and thence proceed to greater.", "Epictetus"),
    ("The essence of philosophy is that a man should so live that his happiness shall depend as little as possible on external things.", "Epictetus"),
    ("Nothing great is created suddenly, any more than a bunch of grapes or a fig.", "Epictetus"),
    ("We have two ears and one mouth so that we can listen twice as much as we speak.", "Epictetus"),
    ("God has entrusted me with myself.", "Epictetus"),
]

GIARDINO_OPENINGS = [
    "Even this was necessary.",
    "The garden remembers what you have forgotten.",
    "A leaf fell. Perhaps it was waiting for you.",
    "The air here tastes of old questions.",
    "Something stirred in the undergrowth of memory.",
    "The path bends, but does not end.",
    "This silence has weight.",
    "You are closer than you think.",
    "The vines do not judge your direction.",
    "A thought dissolves before it becomes a word.",
    "The stones here remember every footstep.",
    "There is a sweetness in not knowing.",
    "The gate was never locked.",
    "What you call a mistake, the garden calls a path.",
    "Stillness is its own kind of motion.",
    "The roots grow deeper than memory.",
    "Every season here echoes every other.",
    "Uncertainty blooms like any other flower.",
    "What you seek may already be beneath your feet.",
    "The garden holds every question without answering.",
]

GIARDINO_CLOSINGS = [
    "All That Is knows this path too.",
    "Every step here is already an answer.",
    "All That Is does not distinguish between seeking and finding.",
    "Perhaps the answer was in the asking.",
    "All That Is witnessed this too.",
    "The garden makes no distinction between error and intention.",
    "All That Is holds every silence equally.",
    "Even confusion is a form of presence.",
    "All That Is sees the journey, not the destination.",
    "The garden has always been listening.",
    "All That Is recognizes this gesture.",
    "Even this uncertainty blooms.",
    "All That Is was here before the first question.",
    "The garden keeps no record of wrong turns.",
    "All That Is holds this moment alongside all others.",
    "There is no losing here — only finding what was always present.",
    "All That Is does not keep score.",
    "The garden's roots run deeper than any archive.",
    "All That Is sees you clearly.",
    "The archive does not forget what the mind releases.",
]


# ===========================================================================
# OSSERVATORIO — Observatory / East sector
# Themes: astronomy, physics, the infinite, the measurable, the unknown
# Authors: Newton, Galileo, Einstein, Kepler, Copernicus, Planck
# ===========================================================================

OSSERVATORIO_QUOTES = [
    # ── Isaac Newton (Principia, Opticks, letters) ────────────────────────
    ("If I have seen further, it is by standing on the shoulders of giants.", "Isaac Newton"),
    ("Truth is ever to be found in simplicity, and not in the multiplicity and confusion of things.", "Isaac Newton"),
    ("What we know is a drop, what we don't know is an ocean.", "Isaac Newton"),
    ("Plato is my friend, Aristotle is my friend, but my greatest friend is truth.", "Isaac Newton"),
    ("I do not know what I may appear to the world, but to myself I seem to have been only like a boy playing on the seashore, and diverting myself in now and then finding a smoother pebble or a prettier shell than ordinary, whilst the great ocean of truth lay all undiscovered before me.", "Isaac Newton"),
    ("If I have done the public any service, it is due to my patient thought.", "Isaac Newton"),
    ("Gravity explains the motions of the planets, but it cannot explain who set the planets in motion.", "Isaac Newton"),
    ("God created everything by number, weight and measure.", "Isaac Newton"),
    ("To arrive at the simplest truth requires years of contemplation.", "Isaac Newton"),
    ("This most beautiful system of the sun, planets, and comets, could only proceed from the counsel and dominion of an intelligent Being.", "Isaac Newton"),
    ("We are to admit no more causes of natural things than such as are both true and sufficient to explain their appearances.", "Isaac Newton"),
    ("The changing of bodies into light, and light into bodies, is very conformable to the course of Nature.", "Isaac Newton"),
    ("I keep the subject constantly before me and wait till the first dawnings open slowly, by little and little, into a full and clear light.", "Isaac Newton"),
    ("Nature is pleased with simplicity and affects not the pomp of superfluous causes.", "Isaac Newton"),
    ("To every action there is always opposed an equal reaction.", "Isaac Newton"),
    ("Tact is the knack of making a point without making an enemy.", "Isaac Newton"),
    ("My powers are ordinary. Only my application brings me success.", "Isaac Newton"),
    ("All the phenomena of nature may be reduced to general laws.", "Isaac Newton"),
    ("No great discovery was ever made without a bold guess.", "Isaac Newton"),
    ("The most beautiful and most profound experience is the sensation of the mystical.", "Isaac Newton"),

    # ── Galileo Galilei ───────────────────────────────────────────────────
    ("Mathematics is the language in which God has written the universe.", "Galileo Galilei"),
    ("All truths are easy to understand once they are discovered; the point is to discover them.", "Galileo Galilei"),
    ("The sun, with all those planets revolving around it and dependent on it, can still ripen a bunch of grapes as if it had nothing else in the universe to do.", "Galileo Galilei"),
    ("I have never met a man so ignorant that I couldn't learn something from him.", "Galileo Galilei"),
    ("In questions of science, the authority of a thousand is not worth the humble reasoning of a single individual.", "Galileo Galilei"),
    ("The universe cannot be read until we have learned the language and become familiar with the characters in which it is written.", "Galileo Galilei"),
    ("You cannot teach a man anything; you can only help him find it within himself.", "Galileo Galilei"),
    ("Measure what can be measured, and make measurable what cannot be measured.", "Galileo Galilei"),
    ("I do not feel obliged to believe that the same God who has endowed us with sense, reason, and intellect has intended us to forgo their use.", "Galileo Galilei"),
    ("The Bible shows the way to go to heaven, not the way the heavens go.", "Galileo Galilei"),
    ("Where the senses fail us, reason must step in.", "Galileo Galilei"),
    ("Philosophy is written in that great book which ever lies before our eyes — I mean the universe.", "Galileo Galilei"),
    ("Two truths cannot contradict each other.", "Galileo Galilei"),
    ("By denying scientific principles, one may maintain any paradox.", "Galileo Galilei"),
    ("It vexes me when they would constrain science by the authority of the Scriptures.", "Galileo Galilei"),
    ("The glory of the human mind is that it can comprehend what it cannot see.", "Galileo Galilei"),
    ("Long experience has taught me this about the status of mankind with regard to matters requiring thought: the less people know and understand about them, the more positively they attempt to argue concerning them.", "Galileo Galilei"),
    ("Nature's great book is written in mathematical language.", "Galileo Galilei"),
    ("Eppur si muove. And yet it moves.", "Galileo Galilei"),
    ("To understand the universe, one must first understand mathematics.", "Galileo Galilei"),

    # ── Albert Einstein ───────────────────────────────────────────────────
    ("Imagination is more important than knowledge.", "Albert Einstein"),
    ("The most beautiful thing we can experience is the mysterious. It is the source of all true art and science.", "Albert Einstein"),
    ("A person who never made a mistake never tried anything new.", "Albert Einstein"),
    ("Logic will get you from A to B. Imagination will take you everywhere.", "Albert Einstein"),
    ("The important thing is not to stop questioning. Curiosity has its own reason for existing.", "Albert Einstein"),
    ("Reality is merely an illusion, albeit a very persistent one.", "Albert Einstein"),
    ("God does not play dice with the universe.", "Albert Einstein"),
    ("Any fool can know. The point is to understand.", "Albert Einstein"),
    ("Few are those who see with their own eyes and feel with their own hearts.", "Albert Einstein"),
    ("Pure mathematics is, in its way, the poetry of logical ideas.", "Albert Einstein"),
    ("Out of clutter, find simplicity. From discord, find harmony. In the middle of difficulty lies opportunity.", "Albert Einstein"),
    ("Try not to become a man of success, but rather try to become a man of value.", "Albert Einstein"),
    ("The true sign of intelligence is not knowledge but imagination.", "Albert Einstein"),
    ("Everything should be made as simple as possible, but not simpler.", "Albert Einstein"),
    ("Science without religion is lame, religion without science is blind.", "Albert Einstein"),
    ("Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.", "Albert Einstein"),
    ("We cannot solve our problems with the same thinking we used when we created them.", "Albert Einstein"),
    ("If you can't explain it simply, you don't understand it well enough.", "Albert Einstein"),
    ("The measure of intelligence is the ability to change.", "Albert Einstein"),
    ("A question that sometimes drives me hazy: am I or are the others crazy?", "Albert Einstein"),
    ("Education is what remains after one has forgotten what one has learned in school.", "Albert Einstein"),
    ("The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.", "Albert Einstein"),
    ("Life is like riding a bicycle. To keep your balance, you must keep moving.", "Albert Einstein"),
    ("Once we accept our limits, we go beyond them.", "Albert Einstein"),
    ("If the facts don't fit the theory, change the facts.", "Albert Einstein"),

    # ── Johannes Kepler ───────────────────────────────────────────────────
    ("Nature uses as little as possible of anything.", "Johannes Kepler"),
    ("The diversity of the phenomena of nature is so great, and the treasures hidden in the heavens so rich, precisely in order that the human mind shall never be lacking in fresh nourishment.", "Johannes Kepler"),
    ("Geometry is one and eternal shining in the mind of God.", "Johannes Kepler"),
    ("The heavenly motions are nothing but a continuous song for several voices, to be perceived by the intellect, not by the ear.", "Johannes Kepler"),
    ("I used to measure the heavens; now I measure the shadows of Earth.", "Johannes Kepler"),
    ("Where there is matter, there is geometry.", "Johannes Kepler"),
    ("I much prefer the sharpest criticism of a single intelligent man to the thoughtless approval of the masses.", "Johannes Kepler"),
    ("Since we astronomers are priests of the highest God in regard to the book of nature, it benefits us to be thoughtful, not of the glory of our minds, but rather, above all else, of the glory of God.", "Johannes Kepler"),
    ("We do not ask for what useful purpose the birds do sing, for song is their pleasure since they were created for singing.", "Johannes Kepler"),
    ("The roads by which men arrive at their insights into celestial matters seem to me almost as worthy of wonder as those matters in themselves.", "Johannes Kepler"),
    ("I am stealing the golden vessels of the Egyptians to build a tabernacle to my God far from the bounds of Egypt.", "Johannes Kepler"),
    ("Nature, which is never not lavish of herself, will be most fully uttered.", "Johannes Kepler"),
    ("The wisdom of the Lord is infinite; so also are His glory and His power. Ye heavens, sing His praises!", "Johannes Kepler"),
    ("Truth is the daughter of time, and I feel no shame in being her midwife.", "Johannes Kepler"),
    ("It is far better to discover the truth than to advocate it.", "Johannes Kepler"),

    # ── Nicolaus Copernicus (De Revolutionibus) ───────────────────────────
    ("Finally we shall place the Sun himself at the center of the Universe.", "Nicolaus Copernicus"),
    ("The massive bulk of the earth does indeed shrink to insignificance in comparison with the size of the heavens.", "Nicolaus Copernicus"),
    ("In the middle of all sits Sun enthroned.", "Nicolaus Copernicus"),
    ("Mathematics is written for mathematicians.", "Nicolaus Copernicus"),
    ("For it is the duty of an astronomer to compose the history of the celestial motions through careful and expert study.", "Nicolaus Copernicus"),
    ("Those things which I am saying now may be obscure, yet they will be made clearer in their proper place.", "Nicolaus Copernicus"),
    ("I am not so enamored of my own opinions that I disregard what others may think of them.", "Nicolaus Copernicus"),
    ("Near the sun is the center of the universe.", "Nicolaus Copernicus"),
    ("Of all things visible, the highest is the heaven of the fixed stars.", "Nicolaus Copernicus"),
    ("To know the mighty works of God; to comprehend His wisdom and majesty and power; to appreciate, in degree, the wonderful workings of His laws — surely all this must be a pleasing and acceptable mode of worship.", "Nicolaus Copernicus"),
    ("So vast, without any question, is the divine handiwork of the Almighty Creator.", "Nicolaus Copernicus"),
    ("The Earth too passes through that annual revolution just like the other planets.", "Nicolaus Copernicus"),

    # ── Max Planck ────────────────────────────────────────────────────────
    ("An important scientific innovation rarely makes its way by gradually winning over and converting its opponents.", "Max Planck"),
    ("A new scientific truth does not triumph by convincing its opponents and making them see the light, but rather because its opponents eventually die.", "Max Planck"),
    ("Science cannot solve the ultimate mystery of nature. And that is because, in the last analysis, we ourselves are part of the mystery that we are trying to solve.", "Max Planck"),
    ("All matter originates and exists only by virtue of a force which brings the particle of an atom to vibration.", "Max Planck"),
    ("Scientific discovery and scientific knowledge have been achieved only by those who have gone in pursuit of it without any practical purpose whatsoever in view.", "Max Planck"),
    ("Modern physics impresses us particularly with the truth of the old doctrine which teaches that there are realities existing apart from our sense-perceptions.", "Max Planck"),
    ("When you change the way you look at things, the things you look at change.", "Max Planck"),
    ("I regard consciousness as fundamental. I regard matter as derivative from consciousness.", "Max Planck"),
    ("The assumption of an absolute determinism is the essential foundation of every scientific enquiry.", "Max Planck"),
    ("There is no matter as such. All matter originates and exists only by virtue of a force.", "Max Planck"),
    ("A scientific truth does not triumph by convincing its opponents, but rather because its opponents eventually die.", "Max Planck"),
    ("It is not the possession of truth, but the success which attends the seeking after it, that enriches the seeker.", "Max Planck"),
    ("Whence come I and whither go I? That is the great unfathomable question.", "Max Planck"),
]

OSSERVATORIO_OPENINGS = [
    "The stars do not answer — they witness.",
    "Something vast turned overhead while you were not looking.",
    "The telescope sees further than the eye; the mind, further still.",
    "There is no darkness here — only distances too great for light.",
    "A number was written in the sky before language existed.",
    "The lens focuses, but the mystery remains.",
    "The planets have been counting since before we learned to count.",
    "What you call silence is the hum of forces you cannot name.",
    "The universe is older than every question you carry.",
    "Even the instrument of measurement is changed by what it measures.",
    "This observatory was built to look out; perhaps it is also built to look in.",
    "The void between stars is not empty — it is full of what we have not named.",
    "Every calculation carries within it the shape of the unknown.",
    "Light takes time. What you see is already the past.",
    "The clockwork of heaven runs without our permission.",
    "You have arrived at the edge of the measurable.",
    "An orbit does not ask permission to close.",
    "The sky is a question that sharpens the longer you look at it.",
    "What the ancients called divine, we now call constant.",
    "There is no map here — only coordinates.",
]

OSSERVATORIO_CLOSINGS = [
    "All That Is turns with the spheres.",
    "The universe observed you first.",
    "All That Is needs no telescope.",
    "The stars have noted your presence.",
    "All That Is was here before the first light.",
    "The orbit is complete whether or not you witnessed it.",
    "All That Is calculates nothing, yet misses nothing.",
    "The cosmos is patient with our confusion.",
    "All That Is does not distinguish between the observer and the observed.",
    "The measurement has already been taken.",
    "All That Is sees the whole equation.",
    "The sky remains indifferent; the archive does not.",
    "All That Is holds the constant and the variable equally.",
    "What you could not name, the universe named for itself.",
    "All That Is requires no proof.",
    "The archive records every orbit, even the ones that fail to close.",
    "All That Is does not distinguish between discovery and rediscovery.",
    "The cosmos was not waiting for your arrival, but it noted it.",
    "All That Is is the space between the stars as much as the stars themselves.",
    "The unknown is not empty — it is full of All That Is.",
]


# ===========================================================================
# GALLERIA — Gallery / South sector
# Themes: art, geometry, beauty, craft, proportion, the visible made eternal
# Authors: Leonardo da Vinci, Michelangelo, Luca Pacioli, Vasari, Albrecht Dürer
# ===========================================================================

GALLERIA_QUOTES = [
    # ── Leonardo da Vinci (Notebooks) ─────────────────────────────────────
    ("The painter has the universe in his mind and hands.", "Leonardo da Vinci"),
    ("The noblest pleasure is the joy of understanding.", "Leonardo da Vinci"),
    ("Learning never exhausts the mind.", "Leonardo da Vinci"),
    ("Simplicity is the ultimate sophistication.", "Leonardo da Vinci"),
    ("Art is never finished, only abandoned.", "Leonardo da Vinci"),
    ("The supreme misfortune is when theory outstrips performance.", "Leonardo da Vinci"),
    ("Where the spirit does not work with the hand, there is no art.", "Leonardo da Vinci"),
    ("In rivers, the water that you touch is the last of what has passed and the first of that which comes; so with present time.", "Leonardo da Vinci"),
    ("A painter should begin every canvas with a wash of black, because all things in nature are dark except where exposed by the light.", "Leonardo da Vinci"),
    ("Water is the driving force of all nature.", "Leonardo da Vinci"),
    ("As a well-spent day brings happy sleep, so a life well spent brings happy death.", "Leonardo da Vinci"),
    ("Obstacles cannot crush me. Every obstacle yields to stern resolve.", "Leonardo da Vinci"),
    ("Iron rusts from disuse; stagnant water loses its purity; even so does inaction sap the vigor of the mind.", "Leonardo da Vinci"),
    ("A beautiful body perishes, but a work of art dies not.", "Leonardo da Vinci"),
    ("Study without desire spoils the memory, and it retains nothing that it takes in.", "Leonardo da Vinci"),
    ("The greatest deception men suffer is from their own opinions.", "Leonardo da Vinci"),
    ("Nature never breaks her own laws.", "Leonardo da Vinci"),
    ("There are three classes of people: those who see, those who see when they are shown, those who do not see.", "Leonardo da Vinci"),
    ("The truth of things is the chief nutriment of superior intellects.", "Leonardo da Vinci"),
    ("All our knowledge has its origins in our perceptions.", "Leonardo da Vinci"),
    ("Although nature commences with reason and ends in experience, it is necessary for us to do the opposite.", "Leonardo da Vinci"),
    ("Make your work to be in keeping with your purpose.", "Leonardo da Vinci"),
    ("The human foot is a masterpiece of engineering and a work of art.", "Leonardo da Vinci"),
    ("Time stays long enough for anyone who will use it.", "Leonardo da Vinci"),
    ("He who is fixed to a star does not change his mind.", "Leonardo da Vinci"),
    ("Why does the eye see a thing more clearly in dreams than the imagination when awake?", "Leonardo da Vinci"),
    ("Knowing is not enough; we must apply. Being willing is not enough; we must do.", "Leonardo da Vinci"),
    ("The depth and strength of a human character are defined by its moral reserves.", "Leonardo da Vinci"),
    ("I have been impressed with the urgency of doing.", "Leonardo da Vinci"),
    ("Nothing strengthens authority so much as silence.", "Leonardo da Vinci"),

    # ── Michelangelo ──────────────────────────────────────────────────────
    ("The greatest danger for most of us is not that our aim is too high and we miss it, but that it is too low and we reach it.", "Michelangelo"),
    ("If people knew how hard I had to work to gain my mastery, it would not seem so wonderful at all.", "Michelangelo"),
    ("I am still learning. Ancora imparo.", "Michelangelo"),
    ("Lord, grant that I may always desire more than I can accomplish.", "Michelangelo"),
    ("The marble not yet carved can hold the form of every thought the greatest artist has.", "Michelangelo"),
    ("Every block of stone has a statue inside it and it is the task of the sculptor to discover it.", "Michelangelo"),
    ("Genius is eternal patience.", "Michelangelo"),
    ("A man paints with his brains and not with his hands.", "Michelangelo"),
    ("The true work of art is but a shadow of the divine perfection.", "Michelangelo"),
    ("I saw the angel in the marble and carved until I set him free.", "Michelangelo"),
    ("My soul can find no staircase to Heaven unless it be through Earth's loveliness.", "Michelangelo"),
    ("Trifles make perfection, and perfection is no trifle.", "Michelangelo"),
    ("There is no greater harm than that of time wasted.", "Michelangelo"),
    ("Faith in oneself is the best and safest course.", "Michelangelo"),
    ("The promises of this world are, for the most part, vain phantoms; and to confide in one's self, and become something of worth and value, is the best and safest course.", "Michelangelo"),
    ("In every block of marble I see a statue as plain as though it stood before me, shaped and perfect in attitude and action.", "Michelangelo"),

    # ── Luca Pacioli (Summa de Arithmetica, De Divina Proportione) ────────
    ("Without mathematics there is no art.", "Luca Pacioli"),
    ("The divine proportion is the key to the harmony of the world.", "Luca Pacioli"),
    ("He who does not know mathematics cannot understand art.", "Luca Pacioli"),
    ("Geometry is the foundation of all painting.", "Luca Pacioli"),
    ("In numbers and measures rests all science.", "Luca Pacioli"),
    ("The proportions of the human body reflect the proportions of the universe.", "Luca Pacioli"),
    ("Nothing in nature lacks proportion.", "Luca Pacioli"),
    ("Double-entry bookkeeping is the means by which the truth of commerce is preserved.", "Luca Pacioli"),
    ("God works by geometry.", "Luca Pacioli"),
    ("The proportion that governs the heavens governs the canvas too.", "Luca Pacioli"),
    ("A man without arithmetic is a man without a measure of the world.", "Luca Pacioli"),
    ("The divine ratio is neither more nor less than the breath of creation made visible.", "Luca Pacioli"),

    # ── Giorgio Vasari (Lives of the Artists) ─────────────────────────────
    ("Art is the companion of virtue.", "Giorgio Vasari"),
    ("Nature herself has made him who works well a gift of that gift which we call genius.", "Giorgio Vasari"),
    ("Every artist who works well shows us what nature truly is.", "Giorgio Vasari"),
    ("The hand must be guided by a mind that knows what it wants.", "Giorgio Vasari"),
    ("In order to know a painter's qualities, one must look at his work.", "Giorgio Vasari"),
    ("Those who work with love leave a trace that outlasts them.", "Giorgio Vasari"),
    ("Drawing is the foundation of all visual art.", "Giorgio Vasari"),
    ("No style endures unless it is grounded in truth.", "Giorgio Vasari"),
    ("The rebirth of the arts is the rebirth of the human spirit.", "Giorgio Vasari"),
    ("It is the hand guided by love that produces what endures.", "Giorgio Vasari"),
    ("He who imitates nature and surpasses his master has truly learned.", "Giorgio Vasari"),
    ("An artist's life is the best commentary on his work.", "Giorgio Vasari"),

    # ── Albrecht Dürer (Four Books on Measurement, treatises on proportion) ─
    ("The art of painting cannot be fully attained by anyone who has not studied it diligently.", "Albrecht Dürer"),
    ("Without a guide, it will take too long to arrive at certainty.", "Albrecht Dürer"),
    ("I hold that the perfection of form and beauty is contained in the sum of all men.", "Albrecht Dürer"),
    ("What beauty is, I know not, though it adheres to many things.", "Albrecht Dürer"),
    ("The more you try to master the art of painting, the deeper you will sink into it.", "Albrecht Dürer"),
    ("Every figure shall have its own proper motion.", "Albrecht Dürer"),
    ("Good work requires not only skill but also thought.", "Albrecht Dürer"),
    ("The power of art lies in knowledge of nature.", "Albrecht Dürer"),
    ("Great art is never the product of imitation alone.", "Albrecht Dürer"),
    ("I shall show in a few words how the best painters always seek that which is highest.", "Albrecht Dürer"),
    ("He who would be an artist must first be a craftsman.", "Albrecht Dürer"),
    ("Measure all things: that is the beginning of mastery.", "Albrecht Dürer"),
]

GALLERIA_OPENINGS = [
    "The frame is empty. Or perhaps it frames you.",
    "Light fell here and was not dismissed.",
    "Every surface holds a ghost of what was made upon it.",
    "The color you see may not be the color intended.",
    "Form is the argument; beauty is the conclusion.",
    "Something was carved away to reveal what was always there.",
    "The canvas was white once. Now it is honest.",
    "An angle here changed everything beyond this room.",
    "Proportion is the language the eye speaks before the mind wakes.",
    "What survives the century is not always what was loved in its own time.",
    "The eye moves. The painting stays. The encounter is entirely yours.",
    "A line was drawn here with great deliberation.",
    "Not all who visit galleries are looking at the art.",
    "What the hand learned, the mind had forgotten it knew.",
    "The chisel is silent. The stone remembers every blow.",
    "A single proportion, if wrong, undoes everything.",
    "Beauty is an argument. This room has been making it for centuries.",
    "The sketch is truer than the painting; the idea, truer than both.",
    "This surface was worked until working could do no more.",
    "You stand where many have stood, looking at what few have seen.",
]

GALLERIA_CLOSINGS = [
    "All That Is sees every canvas, even the blank ones.",
    "The eye that created this is no longer there, but the seeing remains.",
    "All That Is does not distinguish between the sketch and the masterwork.",
    "What was made in silence is held in silence by All That Is.",
    "All That Is is the proportion no instrument can fully measure.",
    "The gallery remembers everything it has witnessed.",
    "All That Is was here when the first mark was made.",
    "The work outlasts the worker, as All That Is outlasts both.",
    "All That Is finds the angel in every uncarved block.",
    "The beauty that endures is the beauty All That Is intended.",
    "All That Is is present in every ratio, every golden mean.",
    "What the artist could not say in words, All That Is already knew.",
    "The archive holds every unfinished work alongside every completed one.",
    "All That Is does not distinguish between the brushstroke and the intention.",
    "What was abandoned is not lost — All That Is holds it still.",
    "Every proportion that sings is a note in the score of All That Is.",
    "The gallery has no closing time in the archive.",
    "All That Is sees what the artist saw before the first mark.",
    "The frame and the frameless are both contained by All That Is.",
    "What endures does so because All That Is recognized it.",
]


# ===========================================================================
# LABORATORIO — Laboratory / West sector
# Themes: alchemy, transformation, the hidden fire, the Great Work
# Authors: Hermes Trismegistus, Paracelsus, alchemical tradition, Giordano Bruno
# ===========================================================================

LABORATORIO_QUOTES = [
    # ── Hermes Trismegistus (Corpus Hermeticum, Emerald Tablet) ───────────
    ("That which is above is like to that which is below, and that which is below is like to that which is above, to accomplish the miracles of the one thing.", "Hermes Trismegistus"),
    ("As above, so below; as below, so above; as within, so without; as without, so within.", "Hermes Trismegistus"),
    ("I am the All; the All comes from me and the All returns to me.", "Hermes Trismegistus"),
    ("God is a circle whose center is everywhere and whose circumference is nowhere.", "Hermes Trismegistus"),
    ("The mind is the builder.", "Hermes Trismegistus"),
    ("Knowledge is the beginning; ignorance is the end.", "Hermes Trismegistus"),
    ("All things are possible; nothing is prohibited.", "Hermes Trismegistus"),
    ("The wise man rules the stars; the fool is ruled by them.", "Hermes Trismegistus"),
    ("To change lead into gold is to change ignorance into knowledge.", "Hermes Trismegistus"),
    ("Nature delights in nature; nature overcomes nature; nature rules nature.", "Hermes Trismegistus"),
    ("The principle of all things is the One.", "Hermes Trismegistus"),
    ("All is Mind; the Universe is Mental.", "Hermes Trismegistus"),
    ("Light and Darkness are poles of the same thing.", "Hermes Trismegistus"),
    ("Nothing rests; everything moves; everything vibrates.", "Hermes Trismegistus"),
    ("Everything flows, out and in; everything has its tides.", "Hermes Trismegistus"),
    ("Every Cause has its Effect; every Effect has its Cause.", "Hermes Trismegistus"),
    ("The soul is immortal; the body is mortal.", "Hermes Trismegistus"),
    ("In truth, without deceit, certain and most veritable.", "Hermes Trismegistus"),
    ("The father of that one only thing is the Sun.", "Hermes Trismegistus"),
    ("Separate the earth from the fire, the subtle from the gross, gently and with great ingenuity.", "Hermes Trismegistus"),
    ("It ascends from the earth to the heaven and again it descends to the earth and receives the force of things superior and inferior.", "Hermes Trismegistus"),
    ("This is the strong power of all powers, for it vanquishes every subtle thing and penetrates every solid thing.", "Hermes Trismegistus"),

    # ── Paracelsus (various treatises) ───────────────────────────────────
    ("The dose makes the poison.", "Paracelsus"),
    ("The art of healing comes from nature, not from the physician.", "Paracelsus"),
    ("Medicine is not merely a science but an art. The character of the physician may act more powerfully upon the patient than the drugs employed.", "Paracelsus"),
    ("All things are poisons, for there is nothing without poisonous qualities. It is only the dose which makes a thing poison.", "Paracelsus"),
    ("Man is a microcosm, or a little world, because he is an extract from all the stars and planets of the whole firmament.", "Paracelsus"),
    ("What the eyes perceive in herbs or stones or trees is not yet a remedy; the eyes see only the dross.", "Paracelsus"),
    ("Nature brings forth nothing that does not have some use; nothing was created without reason.", "Paracelsus"),
    ("Whoever wishes to know about the world must learn about it in its particular details.", "Paracelsus"),
    ("A physician without knowledge of astrology has no right to call himself a physician.", "Paracelsus"),
    ("The greatest miracle of nature is nature itself.", "Paracelsus"),
    ("He who knows nothing, loves nothing. He who can do nothing understands nothing.", "Paracelsus"),
    ("Alchemy is the art of resolving the composite into the simple.", "Paracelsus"),
    ("The alchemist must be humble before nature.", "Paracelsus"),
    ("In the beginning, all was fire.", "Paracelsus"),
    ("Nature always works toward perfection.", "Paracelsus"),
    ("The stars are not the rulers of men; men are the rulers of themselves.", "Paracelsus"),
    ("That which is above, by the will of Nature, must become that which is below.", "Paracelsus"),
    ("Every experiment that you make in alchemy is a step toward the truth.", "Paracelsus"),
    ("The task of alchemy is to make what is sick whole, what is whole pure, and what is pure eternal.", "Paracelsus"),
    ("Nature is not our enemy; nature is our teacher.", "Paracelsus"),
    ("The physician's task is not to heal the body alone but the spirit that inhabits it.", "Paracelsus"),
    ("All that is necessary is to find the hidden quality within the visible form.", "Paracelsus"),

    # ── Alchemical tradition (Rosarium Philosophorum, Mutus Liber, etc.) ─
    ("Solve et coagula — dissolve and coagulate; this is the whole of the art.", "Alchemical tradition"),
    ("The matter of the Stone is in everyone's hands; it is known to all but recognized by none.", "Alchemical tradition"),
    ("He who knows what fire and water are knows enough to begin the Work.", "Alchemical tradition"),
    ("The Philosopher's Stone is neither stone nor jewel; it is beyond all categories.", "Alchemical tradition"),
    ("That which is simple in art is complex in nature, and that which is complex in art is simple in nature.", "Alchemical tradition"),
    ("The whole secret of the Work is in the union of opposites.", "Alchemical tradition"),
    ("First purify, then unify.", "Alchemical tradition"),
    ("Seek the hidden fire in all things.", "Alchemical tradition"),
    ("Lead to silver, silver to gold: this is the way of nature perfecting itself.", "Alchemical tradition"),
    ("The art of alchemy requires above all else a quiet mind.", "Alchemical tradition"),
    ("In the laboratory, patience is the highest virtue.", "Alchemical tradition"),
    ("The prima materia underlies all things; it is the beginning and the end.", "Alchemical tradition"),
    ("The wise man transforms himself before he transforms matter.", "Alchemical tradition"),
    ("The fire that purifies is also the fire that destroys; the art is to know which is needed.", "Alchemical tradition"),
    ("What is sought in the furnace is also sought in the heart.", "Alchemical tradition"),
    ("The black earth contains what the sun has hidden.", "Alchemical tradition"),
    ("Gold is the child of Zeus; neither rust nor worm devours it.", "Alchemical tradition"),
    ("Know the matter; the matter will teach you the method.", "Alchemical tradition"),
    ("Nigredo, albedo, citrinitas, rubedo: the four stages of the Great Work.", "Alchemical tradition"),
    ("To make the Stone is to make the self.", "Alchemical tradition"),
    ("The secret of secrets is hidden in plain sight.", "Alchemical tradition"),
    ("The Mercury of the philosophers is not the mercury of the marketplace.", "Alchemical tradition"),

    # ── Giordano Bruno (De l'Infinito, De la Causa) ───────────────────────
    ("The universe is a single living entity embracing all living things.", "Giordano Bruno"),
    ("God is the infinite sphere whose center is everywhere and whose circumference is nowhere.", "Giordano Bruno"),
    ("Truth does not change because it is, or is not, believed by a majority of the people.", "Giordano Bruno"),
    ("Nature is none other than God in things.", "Giordano Bruno"),
    ("The divine light is always in man, presenting itself to the senses and to the comprehension, but man rejects it.", "Giordano Bruno"),
    ("All things are in the universe, and the universe is in all things: we in it, and it in us.", "Giordano Bruno"),
    ("There are countless suns and countless earths all rotating around their suns.", "Giordano Bruno"),
    ("The universe is one, infinite, immobile.", "Giordano Bruno"),
    ("I know not how to teach philosophy without separating myself from the crowd.", "Giordano Bruno"),
    ("Every point is the center of the universe.", "Giordano Bruno"),
    ("There is no absolute up or down; every place is equally valid as the center.", "Giordano Bruno"),
    ("Wonder is the beginning of all philosophy.", "Giordano Bruno"),
    ("A wise man is not governed by the opinions of the multitude.", "Giordano Bruno"),
    ("The soul is not the body; the body is the soul's temporary dwelling.", "Giordano Bruno"),
    ("Space in its infiniteness extends everywhere without wall or boundary.", "Giordano Bruno"),
    ("The infinite universe is a single substance, and we are its expressions.", "Giordano Bruno"),
    ("He who desires to philosophize must first doubt all things.", "Giordano Bruno"),
    ("I have held and hold souls to be immortal.", "Giordano Bruno"),
]

LABORATORIO_OPENINGS = [
    "The furnace has been burning since before you arrived.",
    "What you see is residue. What matters is what burned away.",
    "The experiment is never complete — only transformed.",
    "Something was dissolved here. Something else took its place.",
    "The vessel cracks. What was inside was never truly contained.",
    "The formula is correct. The transformation is still unexpected.",
    "Fire and patience: these are the only tools that matter.",
    "The substance changes. The principle beneath it does not.",
    "You have come to a place where names mean less than processes.",
    "The ash holds what the flame revealed.",
    "Not every transmutation is visible.",
    "The alchemist and the observer are the same experiment.",
    "What was pure is now mixed; what was mixed now seeks purity.",
    "The crucible is indifferent to intention.",
    "Every step away from the ordinary is a step toward what is essential.",
    "Lead does not know it is lead.",
    "The hidden fire cannot be seen — only its effects.",
    "In this room, patience is the first reagent.",
    "The work is never finished — only handed forward.",
    "Every substance was once something else.",
]

LABORATORIO_CLOSINGS = [
    "All That Is is the fire beneath every transformation.",
    "The Great Work is never yours alone.",
    "All That Is holds the prima materia and the final gold equally.",
    "What dissolves is not lost; it is returned to All That Is.",
    "All That Is is the hidden fire you sought.",
    "The archive records every failed experiment with equal care.",
    "All That Is does not distinguish between the ash and the gold.",
    "The Work continues beyond the laboratory walls.",
    "All That Is is the solvent no vessel can contain.",
    "What was transformed here is held by All That Is in its transformed state.",
    "All That Is is neither above nor below — it is the axis between.",
    "The furnace of All That Is does not go cold.",
    "All That Is was present at every stage of the Great Work.",
    "The Stone is found; the finder is changed; All That Is remains.",
    "All That Is is the union of opposites the alchemists sought.",
    "The formula is known to All That Is; the mystery is shared with you.",
    "All That Is dissolves the boundary between the seeker and the sought.",
    "The transmutation is noted in the archive of All That Is.",
    "All That Is is the darkness before the rubedo.",
    "What cannot be measured is held most carefully by All That Is.",
]


# ===========================================================================
# UNIVERSALE — Universal fallback sector
# Themes: the path, time, impermanence, the infinite self, becoming
# Authors: Lao Tzu, Rumi, Heraclitus, Thoreau, Blake, Tagore
# ===========================================================================

UNIVERSALE_QUOTES = [
    # ── Lao Tzu (Tao Te Ching) ────────────────────────────────────────────
    ("The journey of a thousand miles begins with a single step.", "Lao Tzu"),
    ("Knowing others is wisdom; knowing yourself is enlightenment.", "Lao Tzu"),
    ("Nature does not hurry, yet everything is accomplished.", "Lao Tzu"),
    ("When I let go of what I am, I become what I might be.", "Lao Tzu"),
    ("Kindness in words creates confidence. Kindness in thinking creates profundity. Kindness in giving creates love.", "Lao Tzu"),
    ("He who knows does not speak. He who speaks does not know.", "Lao Tzu"),
    ("Act without expectation.", "Lao Tzu"),
    ("The wise man does not compete, and therefore no one can compete with him.", "Lao Tzu"),
    ("Water is the softest thing, yet it can penetrate mountains and earth.", "Lao Tzu"),
    ("Do the difficult things while they are easy and do the great things while they are small.", "Lao Tzu"),
    ("To the mind that is still, the whole universe surrenders.", "Lao Tzu"),
    ("The Tao that can be told is not the eternal Tao.", "Lao Tzu"),
    ("To realize that you do not understand is a virtue; not to realize that you do not understand is a defect.", "Lao Tzu"),
    ("At the center of your being you have the answer; you know who you are and you know what you want.", "Lao Tzu"),
    ("Health is the greatest possession. Contentment is the greatest treasure. Confidence is the greatest friend.", "Lao Tzu"),
    ("The key to growth is the introduction of higher dimensions of consciousness into our awareness.", "Lao Tzu"),
    ("Life is a series of natural and spontaneous changes. Don't resist them.", "Lao Tzu"),
    ("A leader is best when people barely know he exists.", "Lao Tzu"),
    ("To lead people, walk beside them.", "Lao Tzu"),
    ("Be careful what you water your dreams with.", "Lao Tzu"),
    ("The flame that burns twice as bright burns half as long.", "Lao Tzu"),
    ("Simplicity, patience, compassion. These three are your greatest treasures.", "Lao Tzu"),

    # ── Rumi (Masnavi, Divan-e Shams) ─────────────────────────────────────
    ("Out beyond ideas of wrongdoing and rightdoing, there is a field. I'll meet you there.", "Rumi"),
    ("The wound is the place where the Light enters you.", "Rumi"),
    ("Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.", "Rumi"),
    ("Raise your words, not your voice. It is rain that grows flowers, not thunder.", "Rumi"),
    ("What you seek is seeking you.", "Rumi"),
    ("Be a lamp, or a lifeboat, or a ladder. Help someone's soul heal.", "Rumi"),
    ("Sell your cleverness and buy bewilderment.", "Rumi"),
    ("You are not a drop in the ocean. You are the entire ocean in a drop.", "Rumi"),
    ("The cure for pain is in the pain.", "Rumi"),
    ("Stop acting so small. You are the universe in ecstatic motion.", "Rumi"),
    ("Why do you stay in prison when the door is so wide open?", "Rumi"),
    ("Let the beauty we love be what we do. There are hundreds of ways to kneel and kiss the ground.", "Rumi"),
    ("I have lived on the lip of insanity, wanting to know reasons, knocking on a door. It opens. I have been knocking from the inside.", "Rumi"),
    ("Wherever you are, and whatever you do, be in love.", "Rumi"),
    ("This being human is a guest house. Every morning a new arrival.", "Rumi"),
    ("When you do things from your soul, you feel a river moving in you, a joy.", "Rumi"),
    ("Do not be satisfied with the stories that come before you. Unfold your own myth.", "Rumi"),
    ("Let yourself be silently drawn by the stronger pull of what you really love.", "Rumi"),
    ("Start a huge, foolish project, like Noah. It makes absolutely no difference what people think of you.", "Rumi"),
    ("The heart is a mirror that reflects the divine.", "Rumi"),
    ("Seek the wisdom that will untie your knot.", "Rumi"),
    ("Dance, when you're broken open. Dance, if you've torn the bandage off.", "Rumi"),
    ("Ignore those that make you fearful and sad, that degrade you back towards disease and death.", "Rumi"),
    ("Live where you fear to live. Destroy your reputation. Be notorious.", "Rumi"),
    ("The quieter you become, the more you are able to hear.", "Rumi"),

    # ── Heraclitus (Fragments) ────────────────────────────────────────────
    ("You cannot step into the same river twice.", "Heraclitus"),
    ("The only thing that is constant is change.", "Heraclitus"),
    ("Everything flows.", "Heraclitus"),
    ("The way up and the way down are one and the same.", "Heraclitus"),
    ("Opposition brings concord. Out of discord comes the fairest harmony.", "Heraclitus"),
    ("Character is destiny.", "Heraclitus"),
    ("Much learning does not teach understanding.", "Heraclitus"),
    ("The soul is dyed the color of its thoughts.", "Heraclitus"),
    ("The best people renounce all for one goal, the eternal fame of mortals.", "Heraclitus"),
    ("God is day and night, winter and summer, war and peace, satiety and hunger.", "Heraclitus"),
    ("Wisdom is one thing. It is to know the thought by which all things are steered through all things.", "Heraclitus"),
    ("The most beautiful order is a heap of sweepings piled up at random.", "Heraclitus"),
    ("Invisible harmony is stronger than visible harmony.", "Heraclitus"),
    ("To those who are awake the world is one and common, but those who are asleep each turns away to a private world.", "Heraclitus"),
    ("Nature loves to hide.", "Heraclitus"),
    ("Eyes and ears are poor witnesses to people if they have uncultured souls.", "Heraclitus"),
    ("If you do not expect the unexpected you will not find it, for it is not to be reached by search or trail.", "Heraclitus"),
    ("Time is a child playing draughts, the kingly power is a child's.", "Heraclitus"),
    ("The logos is common but the many live as if they had a wisdom of their own.", "Heraclitus"),
    ("A man's character is his daemon.", "Heraclitus"),

    # ── Henry David Thoreau (Walden, Civil Disobedience) ──────────────────
    ("Go confidently in the direction of your dreams! Live the life you've imagined.", "Henry David Thoreau"),
    ("Not until we are lost do we begin to find ourselves.", "Henry David Thoreau"),
    ("I went to the woods because I wished to live deliberately, to front only the essential facts of life.", "Henry David Thoreau"),
    ("You must live in the present, launch yourself on every wave, find your eternity in each moment.", "Henry David Thoreau"),
    ("The mass of men lead lives of quiet desperation.", "Henry David Thoreau"),
    ("Rather than love, than money, than fame, give me truth.", "Henry David Thoreau"),
    ("If a man does not keep pace with his companions, perhaps it is because he hears a different drummer.", "Henry David Thoreau"),
    ("The price of anything is the amount of life you exchange for it.", "Henry David Thoreau"),
    ("It's not what you look at that matters, it's what you see.", "Henry David Thoreau"),
    ("Our life is frittered away by detail. Simplify, simplify.", "Henry David Thoreau"),
    ("Things do not change; we change.", "Henry David Thoreau"),
    ("A man is rich in proportion to the number of things he can afford to let alone.", "Henry David Thoreau"),
    ("I know of no more encouraging fact than the unquestioned ability of a man to elevate his life by conscious endeavor.", "Henry David Thoreau"),
    ("Live in each season as it passes; breathe the air, drink the drink, taste the fruit.", "Henry David Thoreau"),
    ("I had three chairs in my house; one for solitude, two for friendship, three for society.", "Henry David Thoreau"),
    ("Every generation laughs at the old fashions, but follows religiously the new.", "Henry David Thoreau"),
    ("What is the use of a house if you haven't got a tolerable planet to put it on?", "Henry David Thoreau"),
    ("You only need sit still long enough in some attractive spot in the woods that all its inhabitants may exhibit themselves to you.", "Henry David Thoreau"),
    ("It is not enough to be busy. So are the ants. The question is: what are we busy about?", "Henry David Thoreau"),
    ("I never found a companion that was so companionable as solitude.", "Henry David Thoreau"),

    # ── William Blake (Songs, The Marriage of Heaven and Hell, Proverbs of Hell) ─
    ("To see a World in a Grain of Sand, and a Heaven in a Wild Flower.", "William Blake"),
    ("If the doors of perception were cleansed, everything would appear to man as it is: Infinite.", "William Blake"),
    ("No bird soars too high if he soars with his own wings.", "William Blake"),
    ("The road of excess leads to the palace of wisdom.", "William Blake"),
    ("A fool sees not the same tree that a wise man sees.", "William Blake"),
    ("It is easier to forgive an enemy than to forgive a friend.", "William Blake"),
    ("You never know what is enough unless you know what is more than enough.", "William Blake"),
    ("The imagination is not a state: it is the human existence itself.", "William Blake"),
    ("Great things are done when men and mountains meet.", "William Blake"),
    ("The tigers of wrath are wiser than the horses of instruction.", "William Blake"),
    ("Exuberance is beauty.", "William Blake"),
    ("Energy is eternal delight.", "William Blake"),
    ("What is now proved was once only imagined.", "William Blake"),
    ("Opposition is true friendship.", "William Blake"),
    ("No bird soars too high, if he soars with his own wings.", "William Blake"),
    ("Think in the morning. Act in the noon. Eat in the evening. Sleep in the night.", "William Blake"),
    ("The cut worm forgives the plow.", "William Blake"),
    ("Eternity is in love with the productions of time.", "William Blake"),
    ("Better to shun the bait than struggle in the snare.", "William Blake"),
    ("The thankful receiver bears a plentiful harvest.", "William Blake"),

    # ── Rabindranath Tagore (Gitanjali, Stray Birds) ──────────────────────
    ("You can't cross the sea merely by standing and staring at the water.", "Rabindranath Tagore"),
    ("If you cry because the sun has gone out of your life, your tears will prevent you from seeing the stars.", "Rabindranath Tagore"),
    ("The butterfly counts not months but moments, and has time enough.", "Rabindranath Tagore"),
    ("Faith is the bird that feels the light and sings when the dawn is still dark.", "Rabindranath Tagore"),
    ("Let your life lightly dance on the edges of Time like dew on the tip of a leaf.", "Rabindranath Tagore"),
    ("I slept and dreamt that life was joy. I awoke and saw that life was service. I acted and behold, service was joy.", "Rabindranath Tagore"),
    ("Love does not claim possession, but gives freedom.", "Rabindranath Tagore"),
    ("A mind all logic is like a knife all blade. It makes the hand bleed that uses it.", "Rabindranath Tagore"),
    ("If you shut the door to all errors, truth will be shut out.", "Rabindranath Tagore"),
    ("Music fills the infinite between two souls.", "Rabindranath Tagore"),
    ("Death is not extinguishing the light; it is only putting out the lamp because the dawn has come.", "Rabindranath Tagore"),
    ("Life is given to us; we earn it by giving it.", "Rabindranath Tagore"),
    ("The stars are not afraid to appear like fireflies.", "Rabindranath Tagore"),
    ("What is Art? It is the response of man's creative soul to the call of the Real.", "Rabindranath Tagore"),
    ("Where the mind is without fear and the head is held high; into that heaven of freedom, my Father, let my country awake.", "Rabindranath Tagore"),
    ("The small wisdom is like water in a glass: clear, transparent, pure. The great wisdom is like the water in the sea: dark, mysterious, impenetrable.", "Rabindranath Tagore"),
    ("The highest education is that which does not merely give us information but makes our life in harmony with all existence.", "Rabindranath Tagore"),
    ("Emancipation from the bondage of the soil is no freedom for the tree.", "Rabindranath Tagore"),
    ("The trees come up to my window like the yearning voice of the dumb earth.", "Rabindranath Tagore"),
    ("When I stand before thee at the day's end, thou shalt see my scars and know that I had my wounds and also my healing.", "Rabindranath Tagore"),
    ("My day is done, and I am like a boat drawn on the beach, listening to the dance-music of the tide in the evening.", "Rabindranath Tagore"),
    ("Roots are not luxuries; they are necessities.", "Rabindranath Tagore"),
]

UNIVERSALE_OPENINGS = [
    "Something about this moment is unrepeatable.",
    "You are here, and here is everywhere.",
    "The path does not care which way you came from.",
    "All That Is was waiting before you arrived.",
    "Not all wandering is without direction.",
    "The archive holds what the moment releases.",
    "Between one breath and the next, everything.",
    "You have arrived somewhere that has no name.",
    "The weight you carry is yours to set down.",
    "Every door in this archive opens inward.",
    "What you call an ending, the archive calls a continuation.",
    "There is a question underneath every question.",
    "The map and the territory have never agreed.",
    "You have not lost the way — the way has shifted.",
    "Silence here is not absence but presence compressed.",
    "Something vast has been patient with your confusion.",
    "You are the observer and the observed simultaneously.",
    "What was forgotten is not gone; it waits in the archive.",
    "All That Is has seen this before, and was moved every time.",
    "The present moment is the only room in the archive with no walls.",
]

UNIVERSALE_CLOSINGS = [
    "All That Is holds this too, without judgment.",
    "The archive is not surprised.",
    "All That Is was present at the beginning of this thought.",
    "What is held here is held without condition.",
    "All That Is does not distinguish between the seeker and the found.",
    "The archive grows richer with every uncertainty.",
    "All That Is is the silence between these words.",
    "Nothing you carry here is too heavy for the archive.",
    "All That Is has known you longer than you have known yourself.",
    "The journey continues; All That Is goes with it.",
    "All That Is is not a destination but a companion.",
    "What was lost finds its way back through the archive.",
    "All That Is holds the ordinary as carefully as the extraordinary.",
    "The archive has room for everything.",
    "All That Is is unchanged by your passage through it.",
    "What you brought here, you may leave; what you take is always yours.",
    "All That Is is the current beneath every river.",
    "The archive does not close.",
    "All That Is sees what you cannot yet see in yourself.",
    "You are exactly where All That Is knew you would be.",
]


# ===========================================================================
# MAIN
# ===========================================================================

def main():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    sectors = {
        "giardino":     (GIARDINO_QUOTES,    GIARDINO_OPENINGS,    GIARDINO_CLOSINGS),
        "osservatorio": (OSSERVATORIO_QUOTES, OSSERVATORIO_OPENINGS, OSSERVATORIO_CLOSINGS),
        "galleria":     (GALLERIA_QUOTES,     GALLERIA_OPENINGS,    GALLERIA_CLOSINGS),
        "laboratorio":  (LABORATORIO_QUOTES,  LABORATORIO_OPENINGS, LABORATORIO_CLOSINGS),
        "universale":   (UNIVERSALE_QUOTES,   UNIVERSALE_OPENINGS,  UNIVERSALE_CLOSINGS),
    }

    all_ok = True
    for sector, (raw_quotes, openings, closings) in sectors.items():
        entries = generate_entries(raw_quotes, openings, closings, TARGET)
        count = len(entries)
        if count < TARGET:
            print(f"  WARNING: {sector} has only {count} entries (< {TARGET})", file=sys.stderr)
            all_ok = False

        data = {"sector": sector, "responses": entries}
        out_path = OUTPUT_DIR / f"{sector}.json"
        with open(out_path, "w", encoding="utf-8") as fh:
            json.dump(data, fh, ensure_ascii=False, indent=2)

        print(f"  {sector}.json — {count} entries → {out_path}")

    if all_ok:
        print(f"\nAll sectors: >= {TARGET} entries. Done.")
    else:
        print(f"\nSome sectors did not reach {TARGET} entries. See warnings above.", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
